import type { Animal } from "@/types";

export const MOCK_ANIMALS: Animal[] = [
  {
    id: "mock-1",
    name: "AV-BOER-DOE-001",
    breed: "Boer",
    type: "Goat",
    purpose: ["Breeding", "Meat"],
    age_months: 18,
    price: 55000,
    price_visible: true,
    tags: ["Top Genetics", "Breeding Female"],
    description:
      "Classic full-blood Boer doe with excellent conformation. Proven fertility, strong maternal instincts, and fast-growing progeny. Sourced from South African champion lines.",
    genetics_notes:
      "Full-blood Boer. Dam with 185% kidding rate over 3 seasons. Sired by SA Grand Champion buck.",
    images: ["/images/Catalogue/img1.png"],
    status: "Available",
    featured: true,
    slug: "av-boer-doe-001",
  },
  {
    id: "mock-2",
    name: "AV-RM-RAM-002",
    breed: "Red Maasai",
    type: "Sheep",
    purpose: ["Breeding", "Meat"],
    age_months: 30,
    price: undefined,
    price_visible: false,
    tags: ["Indigenous Elite", "Parasite Resistant"],
    description:
      "Prime Red Maasai ram from certified KARI breeding program. Naturally resistant to internal parasites. Perfectly adapted to East African conditions and semi-arid environments.",
    genetics_notes:
      "Certified KARI genetics. Haemonchus contortus resistance score: 9/10. Faecal egg count consistently below 200 EPG without treatment.",
    images: ["/images/Catalogue/img2.png"],
    status: "Available",
    featured: true,
    slug: "av-rm-ram-002",
  },
  {
    id: "mock-3",
    name: "AV-SP-EWE-003",
    breed: "Speckled Persian",
    type: "Sheep",
    purpose: ["Breeding", "Meat"],
    age_months: 36,
    price: 32000,
    price_visible: true,
    tags: ["With Lamb", "Proven Dam", "Top Mothering"],
    description:
      "Outstanding Speckled Persian ewe with a healthy lamb at foot. Exceptional mothering ability, high milk production, and consistent lambing record. Farm-born and raised.",
    genetics_notes:
      "Third-generation AcaciaVelds breeding programme. Lambing rate 175% over 4 seasons. Lamb showing rapid growth — 28 days, 9.4 kg.",
    images: ["/images/Catalogue/img3.png"],
    status: "Available",
    featured: true,
    slug: "av-sp-ewe-003",
  },
  {
    id: "mock-4",
    name: "AV-SP-YNG-004",
    breed: "Speckled Persian",
    type: "Sheep",
    purpose: ["Breeding"],
    age_months: 10,
    price: 18000,
    price_visible: true,
    tags: ["Young Stock", "Ready for Mating"],
    description:
      "Well-grown young Speckled Persian ewe ready for first mating. Strong frame, good rear-end development, and excellent body condition. Raised on farm.",
    genetics_notes:
      "Daughter of AV-SP-EWE-003. Showing early signs of superior growth and conformation.",
    images: ["/images/Catalogue/img4.png"],
    status: "Available",
    featured: false,
    slug: "av-sp-yng-004",
  },
  {
    id: "mock-5",
    name: "AV-BOER-BUCK-005",
    breed: "Boer",
    type: "Goat",
    purpose: ["Breeding"],
    age_months: 24,
    price: 95000,
    price_visible: true,
    tags: ["Imported", "Full-blood", "Champion Line"],
    description:
      "Full-blood Boer buck imported from South Africa. Exceptional muscle conformation, heavily built hindquarters, and outstanding libido. Proven sire with progeny across multiple farms.",
    genetics_notes:
      "100% registered Boer bloodline. Sire: SA Grand Champion. Average kid birth weight 4.3 kg, 90-day weight 34 kg.",
    images: ["/images/Catalogue/img5.png"],
    status: "Available",
    featured: true,
    slug: "av-boer-buck-005",
  },
  {
    id: "mock-6",
    name: "AV-ZEBU-BULL-006",
    breed: "Zebu",
    type: "Cattle",
    purpose: ["Breeding"],
    age_months: 48,
    price: undefined,
    price_visible: false,
    tags: ["Heat Tolerant", "Tick Resistant", "Premium Bull"],
    description:
      "Mature Zebu bull with exceptional tropical genetics. Heat-adapted, tick-resistant, and well-suited for East African conditions. Strong and well-muscled with great siring potential.",
    genetics_notes:
      "East African Zebu bloodline. Naturally adapted for thermo-neutral zone above 35°C. Low-input, high-performance sire.",
    images: ["/images/Catalogue/img6.png"],
    status: "Available",
    featured: false,
    slug: "av-zebu-bull-006",
  },
  {
    id: "mock-7",
    name: "AV-ZEBU-COW-007",
    breed: "Zebu",
    type: "Cattle",
    purpose: ["Breeding", "Dairy"],
    age_months: 60,
    price: 180000,
    price_visible: true,
    tags: ["Proven Dam", "With Calf", "Hardy"],
    description:
      "Prime Zebu cow with calf at foot. Strong maternal instincts, good milking ability, and excellent body condition. Both cow and calf healthy and thriving on pasture.",
    genetics_notes:
      "Three successful calvings. Calf showing good growth at 60 days. Dam milk yield 6L/day.",
    images: ["/images/Catalogue/img7.png"],
    status: "Available",
    featured: true,
    slug: "av-zebu-cow-007",
  },
  {
    id: "mock-8",
    name: "AV-DAIRY-008",
    breed: "Friesian Cross",
    type: "Cattle",
    purpose: ["Dairy", "Breeding"],
    age_months: 42,
    price: 220000,
    price_visible: true,
    tags: ["High Yield", "With Calf", "Dairy"],
    description:
      "High-production Friesian cross dairy cow with a healthy calf. Currently producing 18L/day. Calm temperament, easy to handle. Ideal for smallholder or commercial dairy operations.",
    genetics_notes:
      "Friesian × Zebu cross. Milk yield 18L/day with 4.1% butterfat. Proven three calvings with live calves.",
    images: ["/images/Catalogue/img8.png"],
    status: "Available",
    featured: true,
    slug: "av-dairy-008",
  },
  {
    id: "mock-9",
    name: "AV-HORSE-GREY-009",
    breed: "Horse",
    type: "Horse",
    purpose: ["Breeding"],
    age_months: 60,
    price: undefined,
    price_visible: false,
    tags: ["Grey Mare", "Calm", "Working Horse"],
    description:
      "Well-conformed grey mare with a calm and reliable temperament. Suitable for work, breeding, or leisure. Sound in all four legs with no known health issues.",
    genetics_notes:
      "Farm-raised. No pedigree on file. Veterinarian-certified sound.",
    images: ["/images/Catalogue/img9.png"],
    status: "Available",
    featured: false,
    slug: "av-horse-grey-009",
  },
  {
    id: "mock-10",
    name: "AV-HORSE-CHEST-010",
    breed: "Horse",
    type: "Horse",
    purpose: ["Breeding"],
    age_months: 48,
    price: undefined,
    price_visible: false,
    tags: ["Chestnut", "Athletic", "Well-trained"],
    description:
      "Strong chestnut stallion with excellent working lines. Athletic build, strong back, and willing disposition. Well-trained and responsive. Suitable for work or breeding.",
    genetics_notes:
      "Veterinarian-certified sound. No known genetic conditions.",
    images: ["/images/Catalogue/img10.png"],
    status: "Available",
    featured: false,
    slug: "av-horse-chest-010",
  },
  {
    id: "mock-11",
    name: "AV-HORSE-PAIR-011",
    breed: "Horse",
    type: "Horse",
    purpose: ["Breeding"],
    age_months: 36,
    price: undefined,
    price_visible: false,
    tags: ["Matched Pair", "Field Ready"],
    description:
      "Matched pair of brown horses — well-tempered and field-ready. Suitable for draft work, transport, or breeding. Both horses are in excellent condition.",
    genetics_notes:
      "Both horses veterinarian-certified. Vaccinated and dewormed.",
    images: ["/images/Catalogue/img11.png"],
    status: "Available",
    featured: false,
    slug: "av-horse-pair-011",
  },
  {
    id: "mock-12",
    name: "AV-SP-EWE-012",
    breed: "Speckled Persian",
    type: "Sheep",
    purpose: ["Breeding", "Meat"],
    age_months: 24,
    price: 28000,
    price_visible: true,
    tags: ["Prime Condition", "Fertile"],
    description:
      "Prime Speckled Persian ewe in excellent body condition. Good frame, strong constitution, and high fertility. Ready for mating season.",
    genetics_notes:
      "Second-generation farm breeding programme. Consistent growth and health records.",
    images: ["/images/Catalogue/img12.png"],
    status: "Available",
    featured: false,
    slug: "av-sp-ewe-012",
  },
  {
    id: "mock-13",
    name: "AV-BLACK-BUCK-013",
    breed: "Black Goat",
    type: "Goat",
    purpose: ["Breeding", "Meat"],
    age_months: 18,
    price: 35000,
    price_visible: true,
    tags: ["Hardy", "Disease Resistant"],
    description:
      "Hardy black goat buck — strong, healthy, and alert. Well-adapted to local conditions. Good libido and siring record. Suitable for crossbreeding programmes.",
    genetics_notes:
      "Local hardy breed. Vaccinated and dewormed. Veterinarian health-certified.",
    images: ["/images/Catalogue/img13.png"],
    status: "Available",
    featured: false,
    slug: "av-black-buck-013",
  },
  {
    id: "mock-14",
    name: "AV-SP-RAM-014",
    breed: "Speckled Persian",
    type: "Sheep",
    purpose: ["Breeding", "Meat"],
    age_months: 20,
    price: 30000,
    price_visible: true,
    tags: ["Unique Markings", "Good Growth"],
    description:
      "Distinctive spotted Speckled Persian ram in excellent condition. Good growth rates, strong frame, and fine wool quality. Ready for service.",
    genetics_notes:
      "Third-generation AcaciaVelds breeding. Consistent weaning weights above breed average.",
    images: ["/images/Catalogue/img14.png"],
    status: "Available",
    featured: true,
    slug: "av-sp-ram-014",
  },
];
